options:
  logging: CLOUD_LOGGING_ONLY
steps:
- args:
  - build
  - -t
  - '{repository}/{DOCKER_TAG}'
  - .
  name: gcr.io/cloud-builders/docker
- args:
  - push
  - '{repository}/{DOCKER_TAG}'
  name: gcr.io/cloud-builders/docker
